### PR TITLE
Drop kodi-wayland

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
Unfortunately, this can only work for Intel as that is all the team-xbmc PPA supports.

On arm we use kodi from the Ubuntu 20.04 archive (which still needs kodi-wayland).

**Comment by Saviq** [comment]
> Unfortunately, this can only work for Intel as that is all the team-xbmc PPA supports.
> 
> On arm we use kodi from the Ubuntu 20.04 archive (which still needs kodi-wayland).

Fixed. Should be good across the archs.

**Review by AlanGriffiths — APPROVED** [review]
Works on Intel, but with a caveat: the number of working plugins with the new Kodi is concerning.

Appears to preserve the arm packaging.

Let's merge it. but we should take some time before pushing to stable. (Maybe a good time to use candidate!)

bors merge

**Comment by Saviq** [comment]
> the number of working plugins with the new Kodi is concerning.

It's gonna improve with time, hopefully. It doesn't look too bad looking at the available list, I thought? Like, I see 107 video ones?

**Comment by AlanGriffiths** [comment]
> It doesn't look too bad looking at the available list, I thought? Like, I see 107 video ones?

Where do you see that? I see no video ones. (Or are we doing something different? I started with an existing `stable` install and refreshed to the PR.)

**Comment by Saviq** [comment]
> Where do you see that? I see no video ones. (Or are we doing something different? I started with an existing `stable` install and refreshed to the PR.)

I had that until I added `python3` to the snap. Do you still not see them with the latest snap? What about when you search for the "YouTube" addon and try to install it?

**Pull request merged**
